version: "2"
services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    stdin_open: true
    tty: true
    entrypoint: dockerize -wait tcp://redis:6379 -timeout 120s
    depends_on:
      - redis

  webpack:
    image: node:14
    volumes:
      - .:/app
    env_file:
      - .env
    command:
      bash -c "
        npm set unsafe-perm true
        && npm install
        && npm run watch
      "
    working_dir: /app

  redis:
    image: redis:5
