version: "2"
services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    stdin_open: true
    tty: true
    entrypoint: dockerize -wait tcp://redis:6379 -timeout 120s
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis

  redis:
    image: redis:5
