version: 2.1
jobs:
  unit-tests:
    docker:
        - image: 'circleci/python:3.9.5'
        - image: 'redis:5'
    steps:
        - checkout
        - run:
            name: Install system deps
            command:
              sudo apt-get update && sudo apt-get install -y nodejs npm
        - run:
            name: Install Python deps
            command: pip install -r requirements.txt -r requirements-dev.txt
        - run:
            name: Webpack build
            command:
              npm install && npm run build
        - run:
            name: Make directory for test output
            command: mkdir -p test-reports/unit-test
        - run:
            name: Running tests
            command:
                pytest --junitxml=test-reports/unit-test/report.xml
        - store_test_results:
            path: ./test-reports/


workflows:
    version: 2
    export-support:
        jobs:
            - unit-tests
