name: Django CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [ "master" ]

jobs:
  unit_tests_and_coverage:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:5
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install pytest-cov
        pip install pytest-django
        pip install pytest-mock
        pip install pytest-redis
        npm install webpack-bundle-tracker
        npm run build
    - name: Setup Env Variables
      run: |
        cp .env.template .env
    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: export_support.settings.tests
        SENTRY_DSN: ~
        SENTRY_ENVIRONMENT: ~
        DIRECTORY_FORMS_API_HEALTHCHECK_URL: http://example.com/healthcheck
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        REDIS_URL: "redis://localhost:6379"
      run: |
        pytest
    - name: Report code coverage
      uses: codecov/codecov-action@v1
